"""
OneNote Integration Examples
Demonstrates the four main use cases for OneNote as central knowledge repository:
1. Reference data in reports
2. Automated note creation
3. Search and retrieve information
4. Centralize research findings
"""

import sys
from pathlib import Path
from datetime import datetime

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'src'))

from utils.workflow_helpers import OneNoteHelper, ReportBuilder, EmailHelper


# =======================
# USE CASE 1: REFERENCE DATA IN REPORTS
# =======================

def example_1_extract_project_facts_to_report():
    """
    Extract project facts from OneNote and create an Excel status report.

    Use Case: Weekly status report that pulls key metrics from OneNote pages
    """
    print("=" * 60)
    print("EXAMPLE 1: Reference Data in Reports")
    print("=" * 60)

    # Initialize OneNote helper
    onenote = OneNoteHelper(
        default_notebook='Project Knowledge',
        default_section='Metrics'
    )

    # Extract facts from OneNote page
    facts = onenote.extract_facts_for_report(
        notebook='Project Knowledge',
        section='Metrics',
        page_title='Q4 Project Metrics'
    )

    # Create Excel report with OneNote data
    report = ReportBuilder()

    # Add title sheet
    report.add_title_sheet(
        title="Q4 Status Report",
        subtitle=datetime.now().strftime("%Y-%m-%d"),
        metadata={
            "Source": facts['source'],
            "Extracted": facts['extracted_at'],
            "Generated By": "Automation Hub"
        }
    )

    # Add project facts from OneNote tables
    if facts['tables']:
        for i, table in enumerate(facts['tables'], 1):
            if table:  # Make sure table has data
                headers = table[0] if table else []
                data = table[1:] if len(table) > 1 else []

                report.add_data_sheet(
                    sheet_name=f"Metrics {i}",
                    data=data,
                    headers=headers,
                    format_header=True
                )

    # Save report
    output_path = str(Path.home() / 'Documents' / 'Q4_Status_Report.xlsx')
    report.save(output_path)

    print(f"✓ Report created: {output_path}")
    print(f"✓ Data sourced from: {facts['source']}")
    print(f"✓ Tables extracted: {len(facts['tables'])}")
    print()


def example_1b_weekly_report_with_onenote_reference():
    """
    Automated weekly report that references OneNote pages with links.
    """
    print("=" * 60)
    print("EXAMPLE 1B: Weekly Report with OneNote References")
    print("=" * 60)

    onenote = OneNoteHelper()

    # Search for recent decisions
    recent_decisions = onenote.search_for_facts(
        query='approved decision',
        notebook='Project Knowledge',
        max_results=5
    )

    # Create report
    report = ReportBuilder()
    report.add_title_sheet(
        title="Weekly Summary",
        subtitle=f"Week of {datetime.now().strftime('%Y-%m-%d')}"
    )

    # Add decisions reference sheet
    if recent_decisions:
        decision_data = []
        for decision in recent_decisions:
            decision_data.append([
                decision.get('title', ''),
                decision.get('notebook_name', ''),
                decision.get('section_name', ''),
                decision.get('snippet', '')[:100]  # First 100 chars
            ])

        report.add_data_sheet(
            sheet_name="Recent Decisions",
            headers=["Decision", "Notebook", "Section", "Summary"],
            data=decision_data
        )

    output_path = str(Path.home() / 'Documents' / 'Weekly_Summary.xlsx')
    report.save(output_path)

    print(f"✓ Weekly report created: {output_path}")
    print(f"✓ Referenced {len(recent_decisions)} OneNote pages")
    print()


# =======================
# USE CASE 2: AUTOMATED NOTE CREATION
# =======================

def example_2_create_meeting_minutes_from_outlook():
    """
    Automatically create OneNote meeting minutes from Outlook meeting.

    Use Case: After every meeting, automatically populate OneNote with structured minutes
    """
    print("=" * 60)
    print("EXAMPLE 2: Automated Note Creation from Outlook")
    print("=" * 60)

    onenote = OneNoteHelper()

    try:
        # Create meeting minutes from Outlook meeting
        page_id = onenote.create_meeting_minutes_from_outlook(
            notebook='Meetings',
            section='Sprint Planning',
            meeting_subject='Sprint 42 Planning Meeting'
        )

        print(f"✓ Meeting minutes created: {page_id}")
        print(f"✓ Source: Outlook calendar")
        print(f"✓ Location: Meetings / Sprint Planning")

    except ValueError as e:
        # Fallback: Manual meeting minutes
        print(f"⚠ Outlook meeting not found: {e}")
        print("Creating manual meeting minutes instead...")

        page_id = onenote.create_meeting_minutes(
            notebook='Meetings',
            section='Sprint Planning',
            meeting_title='Sprint 42 Planning',
            date=datetime.now().strftime('%Y-%m-%d'),
            attendees=['Alice Johnson', 'Bob Smith', 'Carol Davis'],
            agenda=[
                'Review previous sprint results',
                'Discuss Q4 goals',
                'Estimate upcoming tasks',
                'Plan sprint 42'
            ],
            notes="Team discussed Q4 priorities and estimated all major tasks for sprint 42.",
            action_items=[
                {'task': 'Update design docs', 'owner': 'Alice', 'due': '2024-12-12'},
                {'task': 'Review architecture proposal', 'owner': 'Bob', 'due': '2024-12-13'},
                {'task': 'Prepare sprint backlog', 'owner': 'Carol', 'due': '2024-12-11'}
            ]
        )

        print(f"✓ Manual meeting minutes created: {page_id}")

    print()


def example_2b_create_project_status_update():
    """
    Automatically create project status page from current data.
    """
    print("=" * 60)
    print("EXAMPLE 2B: Automated Project Status Update")
    print("=" * 60)

    onenote = OneNoteHelper()

    # Create project status page
    page_id = onenote.create_project_status_page(
        notebook='Projects',
        section='Q4 2024',
        project_name='Homepage Redesign',
        status='On Track',
        progress=75,
        milestones=[
            {'name': 'Design Complete', 'due': '2024-12-01', 'status': 'Done'},
            {'name': 'Development', 'due': '2024-12-15', 'status': 'In Progress'},
            {'name': 'Testing', 'due': '2024-12-20', 'status': 'Not Started'},
            {'name': 'Production Deploy', 'due': '2024-12-22', 'status': 'Not Started'}
        ],
        issues=[
            'Performance testing delayed by 2 days',
            'Need final approval on new color scheme'
        ],
        next_steps=[
            'Complete development by Dec 15',
            'Start QA testing',
            'Schedule stakeholder demo'
        ]
    )

    print(f"✓ Project status page created: {page_id}")
    print(f"✓ Project: Homepage Redesign")
    print(f"✓ Progress: 75%")
    print(f"✓ Location: Projects / Q4 2024")
    print()


# =======================
# USE CASE 3: SEARCH AND RETRIEVE INFORMATION
# =======================

def example_3_search_for_requirements():
    """
    Search OneNote for specific requirements and display results.

    Use Case: Quick lookup of project requirements, decisions, or facts
    """
    print("=" * 60)
    print("EXAMPLE 3: Search and Retrieve Information")
    print("=" * 60)

    onenote = OneNoteHelper()

    # Search for requirements
    print("Searching for 'authentication requirements'...")
    results = onenote.search_for_facts(
        query='authentication requirements',
        notebook='Project Knowledge',
        max_results=10
    )

    print(f"\nFound {len(results)} results:\n")

    for i, result in enumerate(results, 1):
        print(f"{i}. {result.get('title', 'Untitled')}")
        print(f"   Location: {result.get('notebook_name', '')} / {result.get('section_name', '')}")
        print(f"   Snippet: {result.get('snippet', '')[:150]}...")
        print()

    # Get full content from first result
    if results:
        first_result = results[0]
        print(f"Getting full content from: {first_result.get('title', '')}")

        content = onenote.get_page_content(
            notebook=first_result.get('notebook_name', ''),
            section=first_result.get('section_name', ''),
            title=first_result.get('title', ''),
            format='text'
        )

        print(f"\nFull content preview ({len(content)} characters):")
        print("-" * 60)
        print(content[:500] + "..." if len(content) > 500 else content)
        print()


def example_3b_search_and_email_results():
    """
    Search OneNote and email results to stakeholders.
    """
    print("=" * 60)
    print("EXAMPLE 3B: Search and Email Results")
    print("=" * 60)

    onenote = OneNoteHelper()

    # Search for approved decisions
    decisions = onenote.search_for_facts(
        query='approved',
        notebook='Project Knowledge',
        max_results=5
    )

    if decisions:
        # Build email body with results
        email = EmailHelper()

        body = "<html><body>"
        body += "<h2>Recent Approved Decisions</h2>"
        body += "<p>Here are the most recent approved decisions from our project knowledge base:</p>"
        body += "<table border='1' cellpadding='5' cellspacing='0'>"
        body += "<tr><th>Decision</th><th>Location</th><th>Summary</th></tr>"

        for decision in decisions:
            body += "<tr>"
            body += f"<td><b>{decision.get('title', '')}</b></td>"
            body += f"<td>{decision.get('notebook_name', '')} / {decision.get('section_name', '')}</td>"
            body += f"<td>{decision.get('snippet', '')[:100]}...</td>"
            body += "</tr>"

        body += "</table>"
        body += f"<p><i>Generated by Automation Hub on {datetime.now().strftime('%Y-%m-%d %H:%M')}</i></p>"
        body += "</body></html>"

        print(f"✓ Email prepared with {len(decisions)} decisions")
        print("✓ Email ready to send (uncomment send_report to actually send)")

        # Uncomment to actually send:
        # email.send_report(
        #     to=['stakeholders@company.com'],
        #     subject='Recent Approved Decisions - Weekly Update',
        #     body=body
        # )

    print()


# =======================
# USE CASE 4: CENTRALIZE RESEARCH FINDINGS
# =======================

def example_4_aggregate_research_files():
    """
    Aggregate research from multiple files into central OneNote repository.

    Use Case: Collect scattered research files into organized OneNote pages
    """
    print("=" * 60)
    print("EXAMPLE 4: Centralize Research Findings")
    print("=" * 60)

    onenote = OneNoteHelper()

    # Create sample research files (in a real scenario, these would already exist)
    research_dir = Path.home() / 'Documents' / 'Research'
    research_dir.mkdir(exist_ok=True)

    # Create sample files
    sample_files = []

    # Sample 1: Competitor analysis
    file1 = research_dir / 'competitor_analysis.txt'
    file1.write_text("""
    Competitor Analysis - Homepage Performance

    Key Findings:
    - Average load time across top 5 competitors: 2.3 seconds
    - 80% use mobile-first design approach
    - Video content featured prominently on 60% of sites
    - Average Lighthouse score: 85/100

    Recommendations:
    - Optimize our load time to under 2 seconds
    - Implement mobile-first redesign
    - Consider adding hero video
    """)
    sample_files.append(str(file1))
    print(f"✓ Created sample file: {file1.name}")

    # Sample 2: User research
    file2 = research_dir / 'user_research_notes.txt'
    file2.write_text("""
    User Research Session - December 2024

    Participants: 10 users (ages 25-45)

    Top Feedback:
    - Navigation is confusing (8/10 users)
    - Search functionality needs improvement (7/10 users)
    - Overall visual design is appealing (9/10 users)
    - Page load time is acceptable (7/10 users)

    Action Items:
    - Redesign main navigation
    - Enhance search with filters
    - Maintain current visual direction
    """)
    sample_files.append(str(file2))
    print(f"✓ Created sample file: {file2.name}")

    # Sample 3: Technical research
    file3 = research_dir / 'tech_stack_research.txt'
    file3.write_text("""
    Technical Stack Research

    Framework Comparison:
    - React: Most popular, large ecosystem, steep learning curve
    - Vue: Simpler, growing popularity, smaller ecosystem
    - Next.js: Built on React, excellent SSR support, deployment ready

    Recommendation:
    - Use Next.js for new homepage
    - Benefits: SSR for SEO, better performance, modern architecture
    - Risk: Team needs training (2-week ramp-up)
    """)
    sample_files.append(str(file3))
    print(f"✓ Created sample file: {file3.name}")

    # Aggregate all research into OneNote
    print(f"\nAggregating {len(sample_files)} research files into OneNote...")

    page_id = onenote.aggregate_research_to_central_notebook(
        source_files=sample_files,
        central_notebook='Project Knowledge',
        section='Research',
        topic='Homepage Redesign - Comprehensive Research'
    )

    print(f"\n✓ Research aggregated into OneNote page: {page_id}")
    print(f"✓ Location: Project Knowledge / Research")
    print(f"✓ Title: Research: Homepage Redesign - Comprehensive Research")
    print(f"✓ Source files: {len(sample_files)}")
    print()


def example_4b_create_standalone_research_notes():
    """
    Create structured research notes directly in OneNote.
    """
    print("=" * 60)
    print("EXAMPLE 4B: Create Standalone Research Notes")
    print("=" * 60)

    onenote = OneNoteHelper()

    # Create research notes
    page_id = onenote.create_research_notes(
        notebook='Research',
        section='Competitors',
        topic='Q4 2024 Competitor Homepage Analysis',
        source='Web research and analytics data - December 2024',
        key_findings=[
            'Average page load time: 2.3 seconds across top 10 competitors',
            'Mobile traffic accounts for 65% of visits on average',
            '80% feature video content above the fold',
            'Average conversion rate: 3.2% (up from 2.8% last quarter)',
            'Social media integration present on 90% of homepages',
            'Average Lighthouse performance score: 85/100',
            'Personalization features detected on 40% of sites',
            'Average time on homepage: 45 seconds'
        ],
        details="""
        Detailed Analysis:

        Performance Metrics:
        - Fastest site: 1.2s load time
        - Slowest site: 4.1s load time
        - Median: 2.3s

        Design Trends:
        - Minimalist design with bold typography (60%)
        - Dark mode support (40%)
        - Animated elements (75%)
        - Sticky navigation (85%)

        Content Strategy:
        - Hero section with CTA (100%)
        - Customer testimonials (70%)
        - Feature highlights (90%)
        - Blog/News section (55%)

        Technical Stack (where detectable):
        - React/Next.js: 45%
        - Vue: 20%
        - WordPress: 15%
        - Custom: 20%
        """,
        tags=['homepage', 'competitors', 'q4-2024', 'analysis', 'ux']
    )

    print(f"✓ Research notes created: {page_id}")
    print(f"✓ Topic: Q4 2024 Competitor Homepage Analysis")
    print(f"✓ Key findings: 8")
    print(f"✓ Tags: homepage, competitors, q4-2024, analysis, ux")
    print()


# =======================
# COMPLETE WORKFLOW: ALL USE CASES COMBINED
# =======================

def complete_workflow_example():
    """
    Complete workflow combining all four use cases.

    Demonstrates a realistic scenario where OneNote acts as central knowledge hub.
    """
    print("=" * 60)
    print("COMPLETE WORKFLOW: All Use Cases Combined")
    print("=" * 60)
    print("\nScenario: Weekly project status workflow")
    print("-" * 60)

    onenote = OneNoteHelper()

    # Step 1: Aggregate research (Use Case 4)
    print("\n[1/4] Aggregating weekly research...")
    # (In real scenario, research files would be collected throughout the week)
    print("✓ Research centralized in OneNote")

    # Step 2: Create meeting minutes (Use Case 2)
    print("\n[2/4] Creating meeting minutes...")
    meeting_page_id = onenote.create_meeting_minutes(
        notebook='Meetings',
        section='Weekly Status',
        meeting_title=f'Weekly Status - {datetime.now().strftime("%Y-%m-%d")}',
        date=datetime.now().strftime('%Y-%m-%d'),
        attendees=['Product Owner', 'Tech Lead', 'Design Lead'],
        agenda=['Review progress', 'Discuss blockers', 'Plan next week'],
        action_items=[
            {'task': 'Complete user testing', 'owner': 'Design Lead', 'due': '2024-12-15'}
        ]
    )
    print(f"✓ Meeting minutes created: {meeting_page_id}")

    # Step 3: Search for key information (Use Case 3)
    print("\n[3/4] Searching for key decisions and requirements...")
    search_results = onenote.search_for_facts(
        query='approved',
        notebook='Project Knowledge',
        max_results=5
    )
    print(f"✓ Found {len(search_results)} key decisions")

    # Step 4: Generate report with OneNote data (Use Case 1)
    print("\n[4/4] Generating status report with OneNote references...")

    report = ReportBuilder()
    report.add_title_sheet(
        title="Weekly Status Report",
        subtitle=datetime.now().strftime("%Y-%m-%d"),
        metadata={
            "Generated": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "Meeting Minutes": f"Page ID: {meeting_page_id}",
            "Key Decisions": f"{len(search_results)} referenced"
        }
    )

    # Add decisions to report
    if search_results:
        decision_data = [[d.get('title', ''), d.get('snippet', '')[:100]] for d in search_results]
        report.add_data_sheet(
            sheet_name="Key Decisions",
            headers=["Decision", "Summary"],
            data=decision_data
        )

    output_path = str(Path.home() / 'Documents' / 'Weekly_Status_Complete.xlsx')
    report.save(output_path)
    print(f"✓ Report created: {output_path}")

    print("\n" + "=" * 60)
    print("COMPLETE WORKFLOW FINISHED")
    print("=" * 60)
    print("\nOneNote now serves as your central knowledge repository!")
    print("All project information is organized and easily accessible.")
    print()


# =======================
# MAIN
# =======================

def main():
    """Run all examples."""
    print("\n")
    print("╔" + "═" * 58 + "╗")
    print("║" + " " * 15 + "ONENOTE INTEGRATION EXAMPLES" + " " * 15 + "║")
    print("║" + " " * 10 + "Central Knowledge Repository Use Cases" + " " * 10 + "║")
    print("╚" + "═" * 58 + "╝")
    print()

    print("This script demonstrates how OneNote serves as your")
    print("central knowledge repository for project information.\n")

    # Note: In a production environment, you would have OneNote open with
    # the appropriate notebooks and sections already created

    print("PREREQUISITES:")
    print("- OneNote desktop application installed")
    print("- Notebooks created: 'Project Knowledge', 'Meetings', 'Projects', 'Research'")
    print("- Sections created as needed for each example")
    print("\nNote: Examples will demonstrate the functionality even if")
    print("OneNote is not fully configured. Some operations may fail gracefully.\n")

    input("Press ENTER to continue...")
    print("\n")

    # Run examples
    try:
        example_1_extract_project_facts_to_report()
    except Exception as e:
        print(f"⚠ Example 1 error (expected if OneNote not configured): {e}\n")

    try:
        example_1b_weekly_report_with_onenote_reference()
    except Exception as e:
        print(f"⚠ Example 1B error (expected if OneNote not configured): {e}\n")

    try:
        example_2_create_meeting_minutes_from_outlook()
    except Exception as e:
        print(f"⚠ Example 2 error (expected if OneNote/Outlook not configured): {e}\n")

    try:
        example_2b_create_project_status_update()
    except Exception as e:
        print(f"⚠ Example 2B error (expected if OneNote not configured): {e}\n")

    try:
        example_3_search_for_requirements()
    except Exception as e:
        print(f"⚠ Example 3 error (expected if OneNote not configured): {e}\n")

    try:
        example_3b_search_and_email_results()
    except Exception as e:
        print(f"⚠ Example 3B error (expected if OneNote not configured): {e}\n")

    try:
        example_4_aggregate_research_files()
    except Exception as e:
        print(f"⚠ Example 4 error (expected if OneNote not configured): {e}\n")

    try:
        example_4b_create_standalone_research_notes()
    except Exception as e:
        print(f"⚠ Example 4B error (expected if OneNote not configured): {e}\n")

    try:
        complete_workflow_example()
    except Exception as e:
        print(f"⚠ Complete workflow error (expected if OneNote not configured): {e}\n")

    print("\n╔" + "═" * 58 + "╗")
    print("║" + " " * 20 + "EXAMPLES COMPLETE" + " " * 21 + "║")
    print("╚" + "═" * 58 + "╝")
    print("\nOneNote is now integrated as your central knowledge repository!")
    print("You can use these patterns in your own automation workflows.\n")


if __name__ == '__main__':
    main()
